name: Delete Expired Tokens

on:
  schedule:
    - cron: '*/5 * * * *' # Menjalankan setiap jam (bisa disesuaikan sesuai kebutuhan)
  workflow_dispatch: # Menjalankan secara manual

jobs:
  clean_tokens:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Sesuaikan dengan versi PHP yang Anda gunakan

    - name: Install dependencies
      run: |
        sudo apt-get install php-curl php-json

    - name: Get Tokens from GitHub
      id: get_tokens
      run: |
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -o tokens.json \
             "https://api.github.com/repos/AllJrLwr/AllJrLwr/contents/tokens.json"

    - name: Clean Expired Tokens
      run: |
        # Membaca file tokens.json dan memeriksa setiap token
        php -r '
        $data = json_decode(file_get_contents("tokens.json"), true);
        if (!$data) { echo "Invalid or empty data."; exit(1); }
        
        // Waktu saat ini dalam detik
        $current_time = time();
        
        // Filter token yang expired (lebih dari 60 menit)
        $valid_tokens = array_filter($data, function($token) use ($current_time) {
            $timestamp = strtotime($token["timestamp"]);
            return ($current_time - $timestamp) <= 3600;  // 3600 detik = 60 menit
        });
        
        // Tulis kembali data yang valid ke file
        file_put_contents("tokens.json", json_encode(array_values($valid_tokens), JSON_PRETTY_PRINT));
        ' 

    - name: Commit & Push Updated Tokens
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add tokens.json
        git commit -m "Remove expired tokens"
        git push
