name: Delete Expired Tokens

on:
  schedule:
    - cron: '0 * * * *' # Jalankan setiap jam

jobs:
  clean_expired_tokens:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Tokens
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Ambil file tokens.json
        curl -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3.raw" \
          -L https://api.github.com/repos/${{ github.repository }}/contents/tokens.json \
          -o tokens.json

    - name: Remove Expired Tokens
      id: filter_tokens
      run: |
        # Hitung batas waktu (60 menit yang lalu)
        THRESHOLD=$(date -d '-60 minutes' --utc +%s)
        
        # Filter token yang masih berlaku
        jq --argjson THRESHOLD "$THRESHOLD" \
          '[.[] | select((.timestamp | fromdateiso8601) > $THRESHOLD)]' tokens.json > new_tokens.json

        # Tentukan apakah ada perubahan
        if cmp -s tokens.json new_tokens.json; then
          echo "updated=false" >> $GITHUB_ENV
        else
          mv new_tokens.json tokens.json
          echo "updated=true" >> $GITHUB_ENV
        fi

    - name: Update Tokens in GitHub
      if: env.updated == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Encode tokens.json ke Base64
        ENCODED_CONTENT=$(base64 -w 0 tokens.json)

        # Ambil SHA dari file lama
        SHA=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/contents/tokens.json | jq -r '.sha')

        # Perbarui file tokens.json
        curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d @- https://api.github.com/repos/${{ github.repository }}/contents/tokens.json <<EOF
        {
          "message": "Menghapus token kedaluwarsa",
          "content": "$ENCODED_CONTENT",
          "sha": "$SHA"
        }
        EOF
