name: Delete Token File

on:
  schedule:
    - cron: '*/30 * * * *'  # Menjalankan setiap 30 menit

jobs:
  delete_token:
    runs-on: ubuntu-latest
    steps:
      # Checkout kode repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Hapus file tokens.json
      - name: Delete Token File
        run: |
          if [ -f tokens.json ]; then
            git rm -f tokens.json
            git commit -m "Menghapus tokens.json secara otomatis setelah 30 menit"
            git push
          else
            echo "File tokens.json tidak ditemukan, tidak ada yang dihapus."
          fi
