name: Clean Expired Tokens

on:
  schedule:
    - cron: "*/5 * * * *" # Jalankan setiap 5 menit
  workflow_dispatch: # Bisa dijalankan secara manual

jobs:
  cleanup_tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup timezone
      - name: Set timezone
        run: echo "TZ=Asia/Jakarta" >> $GITHUB_ENV

      # Install jq untuk memproses JSON
      - name: Install jq
        run: sudo apt-get install jq

      # Clean up expired tokens
      - name: Remove expired tokens
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GITHUB_SECRET_KEY: ${{ secrets.GITHUB_SECRET_KEY }}
        run: |
          # Cek apakah file tokens.json ada dan valid
          if [ -f tokens.json ]; then
            echo "File tokens.json ditemukan. Memeriksa apakah JSON valid..."
            # Menampilkan isi file untuk debugging
            cat tokens.json

            # Periksa apakah file JSON valid
            if ! jq empty tokens.json > /dev/null 2>&1; then
              echo "File tokens.json tidak valid. Memperbaiki format JSON..."
              # Tambahkan tanda kurung penutup jika hilang
              sed -i -e 's/,$//' tokens.json   # Hapus koma terakhir (jika ada)
              echo "]" >> tokens.json          # Tambahkan tanda kurung penutup
            fi
          else
            echo "File tokens.json tidak ditemukan. Membuat file kosong..."
            echo "[]" > tokens.json
          fi

          # Periksa apakah file tokens.json kosong
          if [ ! -s tokens.json ]; then
            echo "File tokens.json kosong, menulis ulang dengan format valid..."
            echo "[]" > tokens.json
          fi

          # Hitung waktu saat ini (dalam detik sejak epoch)
          current_time=$(date +%s)

          # Filter token berdasarkan timestamp:
          # - Validasi 1 jam untuk token yang dihasilkan dari website
          # - Validasi 3 jam untuk token yang dihasilkan dari bot Telegram
          jq --argjson current_time "$current_time" '
            [
              .[] | select(
                # Filter untuk token dari website (1 jam kedaluwarsa)
                (
                  .source == "website" and 
                  ($current_time - (.timestamp | gsub("\\.[0-9]+Z$"; "Z") | fromdateiso8601)) < 3600
                ) or
                # Filter untuk token dari Telegram (3 jam kedaluwarsa)
                (
                  .source == "telegram" and
                  ($current_time - (.timestamp | gsub("\\.[0-9]+Z$"; "Z") | fromdateiso8601)) < 18000
                )
              )
            ]
          ' tokens.json > temp_filtered.json

          # Periksa apakah ada perubahan pada file
          if cmp -s tokens.json temp_filtered.json; then
            echo "Tidak ada perubahan. Tidak ada token yang kedaluwarsa."
          else
            mv temp_filtered.json tokens.json
            git config --global user.name "AllJrLwr"
            git config --global user.email "$GH_EMAIL"
            git add tokens.json
            git commit -m "Cleanup expired tokens"
            git push https://AllJrLwr:${GH_TOKEN}@github.com/AllJrLwr/AllJrLwr.git HEAD:main
            echo "Tokens yang kedaluwarsa berhasil dihapus."
          fi
