name: Delete Expired Tokens

on:
  schedule:
    - cron: '*/5 * * * *' # Jalankan setiap 5 menit (dapat disesuaikan)
  workflow_dispatch: # Memungkinkan menjalankan secara manual

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Filter expired tokens
      id: filter_tokens
      run: |
        # Membaca file tokens.json
        if [ ! -f tokens.json ]; then
          echo "File tokens.json tidak ditemukan."
          exit 0
        fi

        # Mendapatkan waktu saat ini dalam detik
        current_time=$(date +%s)

        # Membaca isi tokens.json dan memfilter token yang sudah kadaluarsa
        temp_file=$(mktemp)
        jq '[.[] | select((($current_time - (.timestamp | fromdateiso8601)) / 60) <= 60)]' tokens.json > $temp_file

        # Mengecek apakah ada perubahan
        if cmp -s tokens.json $temp_file; then
          echo "Tidak ada token yang kadaluarsa."
        else
          # Memperbarui file tokens.json dengan token yang valid
          mv $temp_file tokens.json
          echo "Token yang kadaluarsa telah dihapus."
        fi

    - name: Commit and push changes
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add tokens.json
        git commit -m "Menghapus token yang kadaluarsa dari tokens.json"
        git push
