name: Delete Expired Tokens

on:
  schedule:
    - cron: '*/5 * * * *' # Jalankan setiap 5 menit (dapat disesuaikan)
  workflow_dispatch: # Memungkinkan menjalankan secara manual

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Read and filter tokens
      id: cleanup_tokens
      run: |
        const fs = require('fs');
        const path = './tokens.json';

        // Cek apakah file tokens.json ada
        if (!fs.existsSync(path)) {
          console.log('File tokens.json tidak ditemukan.');
          process.exit(0);
        }

        // Baca isi file tokens.json
        const data = JSON.parse(fs.readFileSync(path, 'utf8'));

        // Filter token yang masih aktif (kurang dari 60 menit sejak timestamp)
        const currentTime = new Date();
        const validTokens = data.filter(token => {
          const tokenTime = new Date(token.timestamp);
          const timeDiff = (currentTime - tokenTime) / (1000 * 60); // Dalam menit
          return timeDiff <= 60; // Hanya simpan token yang belum lebih dari 60 menit
        });

        // Simpan perubahan jika ada token yang expired
        if (validTokens.length !== data.length) {
          fs.writeFileSync(path, JSON.stringify(validTokens, null, 2));
          console.log(`${data.length - validTokens.length} token yang expired telah dihapus.`);
          // Tandai perubahan
          process.exit(0);
        } else {
          console.log('Tidak ada token yang expired.');
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add tokens.json
        git commit -m "Cleanup expired tokens from tokens.json"
        git push
