name: Delete Token File

on:
  schedule:
    - cron: '*/1 * * * *'  # Menjalankan setiap 30 menit

permissions:
  contents: write  # Memberikan izin untuk mengubah konten repository

jobs:
  delete_token:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Konfigurasi Git untuk commit
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Cek dan hapus file tokens.json
      - name: Check and Delete Token File
        run: |
          if [ -f tokens.json ]; then
            echo "File tokens.json ditemukan. Menghapusnya sekarang..."
            git rm -f tokens.json
            git commit -m "Menghapus tokens.json secara otomatis setelah 30 menit"
            git push
          else
            echo "File tokens.json tidak ditemukan. Tidak ada yang dihapus."
