name: Delete Expired Tokens

on:
  schedule:
    - cron: '*/5 * * * *' # Menjalankan setiap 5 menit
  workflow_dispatch: # Memungkinkan menjalankan secara manual

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Filter expired tokens and keep only valid ones
      id: filter_tokens
      run: |
        # Membaca file tokens.json
        if [ ! -f tokens.json ]; then
          echo "File tokens.json tidak ditemukan."
          exit 0
        fi

        # Mendapatkan waktu saat ini dalam detik
        current_time=$(date +%s)

        # Menggunakan jq untuk memfilter token yang valid (dalam waktu 60 menit)
        # Mengonversi timestamp ISO 8601 menjadi timestamp Unix dengan 'date'
        filtered_tokens=$(jq --arg current_time "$current_time" '
          map(select(
            ((($current_time | tonumber) - (
              .timestamp | sub("Z$"; "") | fromdateiso8601
            )) / 60) <= 60))
        ' tokens.json)

        # Mengecek apakah ada token yang kadaluarsa dan melakukan update
        echo "$filtered_tokens" > tokens.json

    - name: Commit and push changes if there are updates
      if: steps.filter_tokens.outputs.filtered_tokens != steps.filter_tokens.outputs.original_tokens
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add tokens.json
        git commit -m "Remove expired tokens from tokens.json"
        git push
